CREATE VIEW ARTISTA_VIEW AS
SELECT 
    ARTISTA.id,
    ARTISTA.nombre,
    ARTISTA.oyentes_mensuales,
    ARTISTA.verificado,
    CANCION.id,
    CANCION.nombre,
    CANCION.duracion,
    CANCION.veces_escuchada,
    ALBUM.id,
    ALBUM.nombre,
    PLAYLIST.id
FROM 
    ARTISTA 
LEFT JOIN 
    ALBUM ON ARTISTA.id = ALBUM.ARTISTA_id AND ARTISTA.USUARIO_id = ALBUM.ARTISTA_USUARIO_id
LEFT JOIN 
    CANCION ON ALBUM.id = CANCION.ALBUM_id AND ARTISTA.USUARIO_id = CANCION.USUARIO_id
LEFT JOIN 
    PLAYLIST ON CANCION.PLAYLIST_id = PLAYLIST.id AND CANCION.PLAYLIST_USUARIO_id = PLAYLIST.USUARIO_id;