CREATE VIEW BIBLIOTECA_VIEW AS 
SELECT
    USUARIO.id,
    USUARIO.nombre_usuario,
    PLAYLIST.id,
    PLAYLIST.nombre,
    PLAYLIST.es_publica,
    CANCION.id,
    CANCION.nombre,
    CANCION.me_gusta
FROM USUARIO 
LEFT JOIN PLAYLIST ON USUARIO.id = PLAYLIST.USUARIO_id
LEFT JOIN PLAYLIST_CANCION ON PLAYLIST.id = PLAYLIST_CANCION.PLAYLIST_id
LEFT JOIN CANCION ON PLAYLIST_CANCION.CANCION_id = CANCION.id;