CREATE VIEW BUSQUEDA_VIEW AS
SELECT
    USUARIO.id,
    USUARIO.nombre_usuario,
    BUSQUEDA.id,
    BUSQUEDA.titulo,
    CATEGORIA.id,
    CATEGORIA.nombre,
    BUSQUEDA.categoria_id
FROM USUARIO 
JOIN BUSQUEDA ON USUARIO.id = BUSQUEDA.usuario_id
JOIN CATEGORIA ON BUSQUEDA.categoria_id = CATEGORIA.id;