CREATE VIEW GENERO_VIEW AS
SELECT 
    GENERO.id,
    GENERO.nombre,
    ARTISTA.id,
    ARTISTA.nombre,
    ARTISTA.recomendado,
    CANCION.id,
    CANCION.nombre,
    CANCION.ARTISTA_id
FROM 
    GENERO
LEFT JOIN 
    ARTISTA ON GENERO.id = ARTISTA.GENERO_id
LEFT JOIN 
    CANCION ON ARTISTA.id = CANCION.ARTISTA_id;